on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 'Testing Github action'
        run: pwd
      - name: 'Printing folder contents'
        run: ls
