on:
  push:
    branches:
      - master
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: "Login to Docker hun"
        run: docker login --username ${{ secrets.DOCKERUSERNAME }}  --password ${{ secrets.DOCKERTOKEN }}
      
      - name: "Building Docker Image"
        run: docker build -t ${{ secrets.DOCKERUSERNAME }}/task_sec .

      - name: "Pushing to Docker Hub"
        run: docker push ${{ secrets.DOCKERUSERNAME }}/task_sec